### ISSUE TITLE
A discussion about the brief introduction

### ISSUE THREAD

**Issue by moonsin** [MarioBrosECS/predicting-employee-attrition-Soton-ECS#14]
I have reviewed it, I think it is a good report. well done @hoanjinan

**Comment by hoanjinan** [comment]
I have updated the 2nd version of the brief right now.  Feel free to make some change and comments on https://1drv.ms/w/s!AtdYNJDGWupOgac98e_cczfzgw0H6g .  I will hand this in again if you have made some changes :)

**Comment by moonsin** [comment]
Deadline has passed
